# SITE CONFIGURATION
title: 박대리의 개발일지 # your site title
author: SeabankDeveloper # You :P
description: > # Meta description of Homepage
  실무 개발을 통해 얻은 내용과 업무 노하우등을 공유하는 블로그입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://SeabankDeveloper.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: JungHoBak
  links:
    - https://www.facebook.com/profile.php?id=100011016070136
    - https://github.com/SeabankDeveloper

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Develop', link: '/develop'}
  #- {name: 'Contact', link: '/contact'}

tagline: >
  C#, Hybrid App 개발에 관련된 실무경험을 모은 블로그

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: inblackhole@naver.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  JungHoBak # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: jungHo # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
